// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyNewwRedis.Data;

#nullable disable

namespace MyNewwRedis.Migrations
{
    [DbContext(typeof(DbContextClass))]
    partial class DbContextClassModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyNewwRedis.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("db4e3a92-3321-430e-8e67-2d56bfd3f3ee"),
                            Name = "as-roma-kit"
                        },
                        new
                        {
                            Id = new Guid("bee1ac44-773b-4a04-8e88-50d0d403ec6c"),
                            Name = "barcelona-kit"
                        },
                        new
                        {
                            Id = new Guid("5f55bfff-d164-4afa-ad14-ead5a021d856"),
                            Name = "ac-milan-kit"
                        },
                        new
                        {
                            Id = new Guid("955ad847-4b16-4b12-89af-062d502861b1"),
                            Name = "manchester-united-kit "
                        },
                        new
                        {
                            Id = new Guid("f7d07862-a8d4-499b-ae97-74c86c61666c"),
                            Name = "real-madrid-kit"
                        },
                        new
                        {
                            Id = new Guid("1c64b045-eca3-4131-9a48-66b3a442987b"),
                            Name = "atletico-madrid-kit"
                        },
                        new
                        {
                            Id = new Guid("ccae299f-8ae7-4853-883f-0bb35c8e49ab"),
                            Name = "fenerbahce-kit"
                        },
                        new
                        {
                            Id = new Guid("88f92638-ee76-4176-8158-aeae8d1db891"),
                            Name = "manchester-city-kit"
                        },
                        new
                        {
                            Id = new Guid("372973fb-1d28-46ef-a6b7-a65c9a5eb18c"),
                            Name = "liverpool-kit"
                        },
                        new
                        {
                            Id = new Guid("d4e292c7-11db-405f-a47d-43bdbb250c9d"),
                            Name = "chelsea-kit"
                        },
                        new
                        {
                            Id = new Guid("e5b1b597-c799-4c69-8fb9-bc04f0a4d805"),
                            Name = "arsenal-kit"
                        },
                        new
                        {
                            Id = new Guid("419b2816-905f-4b1e-ae80-dff1b1f0764a"),
                            Name = "juventus-kit"
                        },
                        new
                        {
                            Id = new Guid("dd0969c6-9d65-4ff5-ab51-aae5904009f1"),
                            Name = "tottenham-hotspur-kit"
                        },
                        new
                        {
                            Id = new Guid("1748f290-95e5-4071-a56f-480c54293330"),
                            Name = "porto-kit"
                        },
                        new
                        {
                            Id = new Guid("1619adf3-a205-4e99-9859-0772a4f78f3c"),
                            Name = "sporting-cp-kit"
                        },
                        new
                        {
                            Id = new Guid("07e6c872-9419-4998-b933-d0a58a543c3b"),
                            Name = "benfica-kit"
                        },
                        new
                        {
                            Id = new Guid("09644cdd-5032-49d8-a570-f40eb83ba3d7"),
                            Name = "inter-milan-kit"
                        },
                        new
                        {
                            Id = new Guid("1f3ed169-1536-4ab1-aefc-f5c17a4ad56e"),
                            Name = "dortmund-kit"
                        },
                        new
                        {
                            Id = new Guid("0848bf92-cf05-49ff-bc96-810e2660d241"),
                            Name = "bayern-munchen-kit"
                        },
                        new
                        {
                            Id = new Guid("6877456d-7aff-4e9e-b387-81bdf54c354d"),
                            Name = "paris-saint-germain-kit"
                        },
                        new
                        {
                            Id = new Guid("2b8fc8af-7b8a-4184-8aa1-ee089cdd6b67"),
                            Name = "ajax-kit"
                        },
                        new
                        {
                            Id = new Guid("e28c8383-1d10-45de-8bf2-d183054d29ec"),
                            Name = "bayer-04-leverkusen-kit"
                        },
                        new
                        {
                            Id = new Guid("54c431ab-c1d7-4695-a1d7-e2242ba0f368"),
                            Name = "psv-eindhoven-kit"
                        },
                        new
                        {
                            Id = new Guid("17a3ee69-23c1-4c1a-89bc-ed00dde5fe22"),
                            Name = "ssc-napoli-kit"
                        },
                        new
                        {
                            Id = new Guid("abe9fd3c-ef76-4d50-a220-530ed9200e4c"),
                            Name = "rb-leipzig-kit"
                        },
                        new
                        {
                            Id = new Guid("429f0d31-24ec-4b9a-b750-17a3f5691633"),
                            Name = "galatasaray-kit"
                        },
                        new
                        {
                            Id = new Guid("0f4e6143-1ba2-4a0c-a8bb-b0abaa7bfb31"),
                            Name = "red-star-belgrade-kit"
                        },
                        new
                        {
                            Id = new Guid("d14e8354-5413-4fb3-bae5-748d5d99284b"),
                            Name = "marseille-kit"
                        },
                        new
                        {
                            Id = new Guid("0b4abc68-8115-4a1d-82b4-fd81b6f98b7b"),
                            Name = "lyon-kit"
                        },
                        new
                        {
                            Id = new Guid("04520370-d1c3-4525-b985-8faf32742a73"),
                            Name = "sevilla-kit"
                        },
                        new
                        {
                            Id = new Guid("3bc528af-1aaa-4018-87fa-197e4c35174c"),
                            Name = "celtic-kit"
                        },
                        new
                        {
                            Id = new Guid("84dd1c7f-c39d-4fe3-b9e2-229193a0d2d1"),
                            Name = "lazio-kit"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
